# Number of days of inactivity before an issue becomes stale
daysUntilStale: 45
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - help wanted
  - good first issue
  - enhancement
  - in progress
# Label to use when marking an issue as stale
stale: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been marked as stale due to inactivity.
  Please comment if this is still relevant
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true